### ISSUE TITLE
GET all Users_Books - User can get all their checked-out books

### ISSUE THREAD

**Issue by fentontaylor** [Guten-Reader/guten_reader_api#2]
As a user, I can send a GET request to `/api/v1/users/:id/books` and return all my checked-out books. If the GET request is successful, I will receive a JSON message with each of my books' author, title, and guten_id. I will also receive 200 status code. If the GET request is unsuccessful,  I will receive a 404 not found error and the message "User could not be found".  

Sad path for if user_id not found. 

See requirements below with specific requirements for request and response.

- [x] Complete endpoint
- [x] Account for sad paths 
- [x] Testing including sad path
- [x] Feature deployed to Heroku
- [x] Update README with information about endpoint

**Request**
``` 
GET /api/v1/users/:id/books
Content-Type: application/json
Accept: application/json
```
**Successful Response**
```
status: 200

{ "books": [ 
         { "id": 1,
            "guten_id": 123456,
            "title": "example title", 
            "author": "example author" }, 
          {  "id": 2,
            "guten_id": 789012,
            "title": "example title", 
            "author": "example author" }, 
          {  "id": 3,
            "guten_id": 345678,
            "title": "example title", 
            "author": "example author" } 
          ]}
```

**Unsuccessful Response**
```
status: 404

{ 
   "error": "User could not be found."
}
```

**Comment by MackHalliday** [comment]
Deployed to heroku
